<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Tree.Service.proto

namespace Tree;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tree.DelRequest</code>
 */
class DelRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string index = 1;</code>
     */
    private $index = '';
    /**
     * Generated from protobuf field <code>string key = 2;</code>
     */
    private $key = '';
    /**
     * Generated from protobuf field <code>string chinese = 3;</code>
     */
    private $chinese = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $index
     *     @type string $key
     *     @type string $chinese
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TreeService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string index = 1;</code>
     * @return string
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Generated from protobuf field <code>string index = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkString($var, True);
        $this->index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string chinese = 3;</code>
     * @return string
     */
    public function getChinese()
    {
        return $this->chinese;
    }

    /**
     * Generated from protobuf field <code>string chinese = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setChinese($var)
    {
        GPBUtil::checkString($var, True);
        $this->chinese = $var;

        return $this;
    }

}

