<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Tree.Service.proto

namespace Tree;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>tree.SearchResult</code>
 */
class SearchResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string str = 1;</code>
     */
    private $str = '';
    /**
     * Generated from protobuf field <code>string data = 2;</code>
     */
    private $data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $str
     *     @type string $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TreeService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string str = 1;</code>
     * @return string
     */
    public function getStr()
    {
        return $this->str;
    }

    /**
     * Generated from protobuf field <code>string str = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStr($var)
    {
        GPBUtil::checkString($var, True);
        $this->str = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string data = 2;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>string data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->data = $var;

        return $this;
    }

}

